int aputchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _low(int c);
int _alpha(int c);
int print_sign(int n);
int aabs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
void print_times_table(int n);
